apply plugin: 'com.android.application'

android {
    compileSdkVersion 34
    buildToolsVersion '34.0.0'

    defaultConfig {
        applicationId 'com.example.reader'
        minSdkVersion 14
        targetSdkVersion 34
        versionCode 17
        versionName '1.8.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    namespace 'com.example.reader'
}

dependencies {
}
